
test_that("test numeric month conversions", {
  expect_equal(convert_month(1), "January")
  expect_equal(convert_month(2), "Febraury")
  expect_equal(convert_month(3), "March")
  expect_equal(convert_month(4), "April")
  expect_equal(convert_month(5), "May")
  expect_equal(convert_month(6), "June")
  expect_equal(convert_month(7), "July")
  expect_equal(convert_month(8), "August")
  expect_equal(convert_month(9), "September")
  expect_equal(convert_month(10), "October")
  expect_equal(convert_month(11), "November")
  expect_equal(convert_month(12), "December")
})

test_that("test full character month conversions", {
  expect_equal(convert_month("January"), 1)
  expect_equal(convert_month("Febraury"), 2)
  expect_equal(convert_month("March"), 3)
  expect_equal(convert_month("April"), 4)
  expect_equal(convert_month("May"), 5)
  expect_equal(convert_month("June"), 6)
  expect_equal(convert_month("July"), 7)
  expect_equal(convert_month("August"), 8)
  expect_equal(convert_month("September"), 9)
  expect_equal(convert_month("October"), 10)
  expect_equal(convert_month("November"), 11)
  expect_equal(convert_month("December"), 12)
})

test_that("test partial character month conversions", {
  expect_equal(convert_month("jan"), 1)
  expect_equal(convert_month("FEB"), 2)
  expect_equal(convert_month("Mar"), 3)
  expect_equal(convert_month("apr"), 4)
  expect_equal(convert_month("MAY"), 5)
  expect_equal(convert_month("Jun"), 6)
  expect_equal(convert_month("jul"), 7)
  expect_equal(convert_month("AUG"), 8)
  expect_equal(convert_month("Sept"), 9)
  expect_equal(convert_month("oct"), 10)
  expect_equal(convert_month("NOV"), 11)
  expect_equal(convert_month("Dec"), 12)
})
